######################################################################
# Automatically generated by qmake (2.01a) pon. cze 30 14:44:08 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . 

# Input
HEADERS += aghphonepref2.h
FORMS += aghphonepref2.ui
SOURCES += aghphonepref2.cpp main.cpp
